providers = ["python"]

nixPkgs = [
  "python312",
  "python312Packages.pip", # explicitly ensure pip is available
  "curl",                  # useful for debug if needed
]

[phases.setup]
cmds = [
  "python --version",
  "pip --version"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python Ace.py"
